version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY_URI=${REPO_ECR}
      - echo "$REPOSITORY_URI"
  build:
    commands:
      - echo "Starting build phase on `date`."
      - echo "Finished build phase."
  post_build:
    commands:
      - echo "Starting post-build phase on `date`."
      - echo "Finished CodeBuild build on `date`."

