version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-west-2|docker login --username AWS --password-stdin 190569914001.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=${REPO_ECR}
      - echo "$REPO_ECR"
      - echo "$$IMAGE_REPO_NAME"
      - echo "$REPOSITORY_URI"
  build:
    commands:
      - echo "Starting build phase on `date`."
      - echo "Finished build phase."
  post_build:
    commands:
      - echo "Starting post-build phase on `date`."
      - echo "Finished CodeBuild build on `date`."

