version: 0.2

phases:
  pre_build:
    commands:
      - REGION="us-west-2"
      - ACCOUNT="$(aws ecr describe-repositories|grep "registryId"|uniq|cut -d ":" -f 2|sed 's/[ ,"]//g')"
      - IMAGE_REPO_NAME="$(aws ecr describe-repositories|grep "repositoryUri"|grep node|cut -d ":" -f 2|sed 's/[ ,"]//g'|cut -d "/" -f 2-3)"
      - REPOSITORY_URI="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-west-2|docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
      - echo "$IMAGE_REPO_NAME"
      - echo "$REPOSITORY_URI"
  build:
    commands:
      - echo "Starting build phase on `date`."
      - echo "Finished build phase."
  post_build:
    commands:
      - echo "Starting post-build phase on `date`."
      - echo "Finished CodeBuild build on `date`."

