version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase"
      - echo "Installing kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mkdir -p ~/.local/bin/kubectl && mv ./kubectl ~/.local/bin/kubectl
      - PATH=$PATH:$HOME/bin
      - echo "Testing kubectl install"
      - kubectl version --client
      - echo "Install phase finished"
  pre_build:
    commands:
      - echo "Starting pre_build phase"
      - echo "Setting variables"
      - REGION="us-west-2"
      - ACCOUNT="$(aws ecr describe-repositories|grep "registryId"|uniq|cut -d ":" -f 2|sed 's/[ ,"]//g')"
      - IMAGE_REPO_NAME="$(aws ecr describe-repositories|grep "repositoryUri"|grep node|cut -d ":" -f 2|sed 's/[ ,"]//g'|cut -d "/" -f 2-3)"
      - IMAGE_NAME="$(aws ecr describe-repositories|grep "repositoryUri"|grep node|cut -d ":" -f 2|sed 's/[ ,"]//g'|cut -d "/" -f 3)"
      - REPOSITORY_URI="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - IMAGE_TAG=latest
      - CLUSTER_NAME=$(aws eks list-clusters|sed 's/[ ,"{}:]//g'|sed 's/\]*\[*//g'|sed '/^$/d'|grep -v clusters)
      - echo "Setting kubeconfig"
      - aws eks update-kubeconfig --name $CLUSTER_NAME 
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-west-2|docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
      - echo "$IMAGE_REPO_NAME"
      - echo "$REPOSITORY_URI"
      - echo "Pre-build phase finished"
  build:
    commands:
      - echo "Starting build phase on `date`."
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - kubectl apply -f ./deployment.yaml
      - kubectl apply -f ./portservice.yaml
      - echo "Finished build phase on `date`."
  post_build:
    commands:
      - echo "Starting post-build phase on `date`."
      - docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Finished CodeBuild build on `date`."
