version: 0.2
env:
  variables: [
    {
      "name": AWS_DEFAULT_REGION
      "value": us-west-2
    }
    {
      "name": AWS_ACCOUNT_ID
      "value": 190569914001
    }
    {
      "name": IMAGE_REPO_NAME
      "value": `aws ecr describe-repositories|grep "repositoryUri"|grep node|cut -d ":" -f 2|sed 's/[ ,"]//g'|cut -d "/" -f 2-3`
    }
    {
      "name": REPOSITORY_URI
      "value": $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
    }
    ]

phases:
  pre_build:
    commands:
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region us-west-2|docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "$IMAGE_REPO_NAME"
      - echo "$REPOSITORY_URI"
  build:
    commands:
      - echo "Starting build phase on `date`."
      - echo "Finished build phase."
  post_build:
    commands:
      - echo "Starting post-build phase on `date`."
      - echo "Finished CodeBuild build on `date`."

