---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "node-hn-app-portservice"
  labels:
    app: "node-hn-app-portservice"
spec:
  type: "LoadBalancer"
  selector: 
    app: "node-hn-app"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
